version: '3.9'

services:
  frontend:
    container_name: frontend_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - backend


  backend:
    image: yazanhamdan/docker-compose-edu-backend
    container_name: backend
    ports:
      - 4200:4200
    depends_on:
      - mysql
    environment:
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_DATABASE=urgentnews
      - DB_HOST=mysql
      - PORT=4200

  mysql:
    image: yazanhamdan/mysql-image-cloud
    container_name: mysql
    ports:
      - 3306:3306
